apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-slsa-web
  namespace: demo
  labels:
    app: python-slsa-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-slsa-web
  template:
    metadata:
      labels:
        app: python-slsa-web
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: python-slsa-web
          image: ghcr.io/pecatap/python-slsa-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
