apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-slsa-web
  namespace: demo
  labels:
    app: python-slsa-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-slsa-web
  template:
    metadata:
      labels:
        app: python-slsa-web
    spec:
      # Image pull secrets for GHCR (uncomment if repository is private)
       imagePullSecrets:
         - name: ghcr-creds

      containers:
        - name: python-slsa-web
          image: ghcr.io/pecatap/python-slsa-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000   # change if your app listens on a different port

