apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-web
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-web
  template:
    metadata:
      labels:
        app: mini-web
    spec:
      # uncomment imagePullSecrets if your GHCR repo is private (see below)
      imagePullSecrets:
       - name: ghcr-creds
      containers:
        - name: web
          image: ghcr.io/PecataP/mini-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
