apiVersion: v1
kind: Service
metadata:
  name: mini-web
  namespace: demo
spec:
  type: NodePort
  selector:
    app: mini-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
